Add a scripts launcher
Gandi/react-translate pull request #1
Opened 2016-11-18 11:01 UTC by iamdey

2016-11-18 11:41 UTC, pascalduez requested changes

2016-11-18 11:41 UTC, pascalduez commented on CHANGELOG.md
> +  - Create a scripts launcher
A bit mysterious, more details?

2016-11-18 11:41 UTC, pascalduez commented on README.md
> +The first time you need to create the folder for the locales you want, for example:
"Before the first run you'll need to create one folder per needed locale, for instance:"

2016-11-18 11:41 UTC, pascalduez commented on bin/extract_messages
> +  This script extracts translations from the passed diretory and generates a json file in a fake
`directory`

2016-11-18 13:33 UTC, pascalduez approved these changes

2016-11-19 17:42 UTC, yanndinendal approved these changes

2016-11-21 13:32 UTC, merged