package deprecation
Gandi/react-translate pull request #18
Opened 2018-10-10 12:38 UTC by iamdey

2018-10-10 12:40 UTC, pascalduez approved these changes

2018-10-10 12:45 UTC, iamdey commented
btw, I have no rights to edit repository description, can you do it @pascalduez  ?

2018-10-10 14:14 UTC, pascalduez commented
@iamdey Nope, I can't...

2018-10-10 16:42 UTC, ziir requested changes
Can we add a *visible* depreciation warning as a `postinstall` script as well?

2018-10-10 16:42 UTC, ziir commented on README.md
> +**// DEPRECATED: please consider to use [linguijs](https://lingui.js.org/)**
Can we add: `or other alternatives.`

2018-10-11 07:06 UTC, pascalduez commented
> Can we add a visible depreciation warning as a postinstall script as well?

`npm deprecate @gandi/translate`

2018-10-11 07:13 UTC, Pegase745 commented
> > Can we add a visible depreciation warning as a postinstall script as well?
> 
> `npm deprecate @gandi/translate`

`npm deprecate @gandi/react-translate` ;)

2018-10-11 07:27 UTC, iamdey commented
@ziir I'm not confident with this; please create a new PR. 
I just wanted to act fast.

2018-10-11 07:27 UTC, merged

2018-10-11 08:01 UTC, Pegase745 commented
@iamdey it has been deprecated, see https://www.npmjs.com/package/@gandi/react-translate

2018-10-16 15:52 UTC, yanndinendal commented
:+1: