Improve README about propsNamespace
Gandi/react-translate pull request #8
Opened 2016-11-23 08:25 UTC by iamdey

fix #7

2016-11-23 08:55 UTC, pascalduez requested changes

2016-11-23 08:55 UTC, pascalduez commented on README.md
> +In order to prevent the "Warning: Unknown props" message, you can use the `propsNamespace` option:
Might be interesting to be a bit more didactic here. A link to the [React doc](https://facebook.github.io/react/warnings/unknown-prop.html) ? A statement about the fact that those props are not valid DOM attributes?

> The unknown-prop warning will fire if you attempt to render a DOM element with a prop that is not recognized by React as a legal DOM attribute/property.

2016-11-23 08:55 UTC, pascalduez commented on README.md
> +@withTranslator({ propsNamespace: 'translator' })
```js
static propType = {
  translator: PropTypes.object.isRequired,
};

2016-11-23 09:14 UTC, iamdey commented on README.md
> +In order to prevent the "Warning: Unknown props" message, you can use the `propsNamespace` option:
WDYT? 

```
In order to prevent [unknown
properties](https://facebook.github.io/react/warnings/unknown-prop.html) (and non-standard DOM
attributes), you can use the `propsNamespace` option:
```

2016-11-23 09:17 UTC, yanndinendal commented on README.md
> +@withTranslator({ propsNamespace: 'translator' })
Ideally we could even export a `translatorShape` that users can import, like `react-router` does: https://github.com/ReactTraining/react-router/pull/3349/files.

@iamdey : should I open a "wishlist" issue about this?

2016-11-23 09:24 UTC, yanndinendal commented on README.md
> +In order to prevent the "Warning: Unknown props" message, you can use the `propsNamespace` option:
LGTM, but keep the "Warning: Unknown props" text so users can easily google it, for example:

> ``` markdown
> In order to prevent the [unknown props warning](https://facebook.github.io/react/warnings/unknown-prop.html)
> (and non-standard DOM attributes), you can use the `propsNamespace` option:
> ```

Or even:

> ``` markdown
> In order to prevent the [unknown props warning](https://facebook.github.io/react/warnings/unknown-prop.html)
> (and non-standard DOM attributes), you can use the `propsNamespace` option.
>> ```
>> bundle.js:2009 Warning: Unknown props `formatDate`, `formatNumber`, `formatPrice`, `formatCurrency`, `localize` on <button> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
>> ```
> ```

2016-11-23 09:25 UTC, yanndinendal commented on README.md
> +attributes), you can use the `propsNamespace` option:
Better, but keep the "Warning: Unknown props" text so users can easily google it, for example:

> ``` markdown
> In order to prevent the [unknown props warning](https://facebook.github.io/react/warnings/unknown-prop.html)
> (and non-standard DOM attributes), you can use the `propsNamespace` option:
> ```

Or even:

> ``` markdown
> In order to prevent the [unknown props warning](https://facebook.github.io/react/warnings/unknown-prop.html)
> (and non-standard DOM attributes), you can use the `propsNamespace` option.
>> ```
>> bundle.js:2009 Warning: Unknown props `formatDate`, `formatNumber`, `formatPrice`, `formatCurrency`, `localize` on <button> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
>> ```
> ```

2016-11-23 09:28 UTC, pascalduez commented on README.md
> +    translator: PropTypes.shape({ __: PropTypes.func.isRequired }),
This is gonna warn, cause there's lots of other keys?

2016-11-23 09:28 UTC, pascalduez approved these changes

2016-11-23 09:54 UTC, yanndinendal commented on README.md
> +    translator: PropTypes.shape({ __: PropTypes.func.isRequired }),
Yes, let's either keep `object` or export a `translatorShape` that will be maintained.

2016-11-23 09:57 UTC, ziir commented on README.md
> +In order to prevent the [unknown props warning](https://facebook.github.io/react/warnings/unknown-prop.html)
I wouldn't mention this issue that is more user-code specific, I'd rather talk about possible props clash with another library

2016-11-23 13:37 UTC, merged

2016-11-24 14:09 UTC, iamdey commented on README.md
> +@withTranslator({ propsNamespace: 'translator' })
not useful in my mind : most of the time we require a `__` function not the world.