Attempt at removing lodash dependency.
Gandi/react-translate pull request #9
Opened 2016-11-23 12:55 UTC by ziir

Lodash is a great tool, but I feel like it is a burden for the users to have it fully included as a -heavy- dependency.

Lodash was mainly used in ./bin/ files to iterate over arrays, mapping values,
we can use plain old ES5 and a bit of ES6 (Object.assign - available in Node.js starting from 4.x)

One use of Lodash that I wouldn't replace is lodash/escape, so I've juste updated
the package.json to only require this specific method package.

Related to #6

2016-11-23 13:09 UTC, iamdey requested changes
:100: totally agree to remove lodash

2016-11-23 13:09 UTC, iamdey commented on src/tools/negociateLocale.js
> +function simpleIntersection(array1, array2) {
can you add a unit test for that ?

2016-11-23 13:21 UTC, ziir commented on src/tools/negociateLocale.js
> +function simpleIntersection(array1, array2) {
Don't you think https://github.com/Gandi/react-translate/blob/master/src/tools/negociateLocale-test.js is sufficient ?

2016-11-23 13:22 UTC, iamdey commented on package.json
> +    "lodash.escape": "^4.0.1",
where and how is it used ? 
is it possible to make your own replace, it sounds pretty simple: https://github.com/lodash/lodash/blob/4.17.2/lodash.js#L14212

2016-11-23 13:25 UTC, iamdey commented on src/tools/negociateLocale.js
> +function simpleIntersection(array1, array2) {
right it looks good

2016-11-23 13:25 UTC, ziir commented on package.json
> +    "lodash.escape": "^4.0.1",
See https://github.com/Gandi/react-translate/blob/master/src/tools/enhanceTranslate.js#L54

I'll take a look, thanks for the heads-up

2016-11-23 13:25 UTC, iamdey approved these changes

2016-11-23 13:54 UTC, yanndinendal approved these changes

2016-11-23 16:08 UTC, ziir commented
./bin files are ok, missing lodash.escape replacement and this MR is good to go

2016-11-24 15:11 UTC, ziir commented on package.json
> +    "lodash.escape": "^4.0.1",
Done

2016-11-24 15:18 UTC, iamdey approved these changes
Sounds good

2016-11-24 15:29 UTC, yanndinendal approved these changes

2016-11-24 15:35 UTC, iamdey requested changes
could you rebase on master, I need the new extraction tool to test on my app

2016-11-24 16:06 UTC, iamdey requested changes
add an entry to changelog please

2016-11-24 16:10 UTC, pascalduez approved these changes

2016-11-24 21:03 UTC, cr0cK commented
rebase done.

2016-11-24 21:03 UTC, merged